CREATE TABLE "User" (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR NOT NULL,
    Email VARCHAR NOT NULL,
    Password VARCHAR NOT NULL,
    PhoneNumber VARCHAR,
    IsVerified BOOLEAN DEFAULT FALSE
);

CREATE TABLE Admin (
    ID SERIAL PRIMARY KEY,
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES "User"(ID) ON DELETE CASCADE
);

CREATE TABLE Technician (
    ID SERIAL PRIMARY KEY,
    UserID INT NOT NULL,
    Specialization VARCHAR,
    Availability TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES "User"(ID) ON DELETE CASCADE
);

CREATE TABLE Customer (
    ID SERIAL PRIMARY KEY,
    UserID INT NOT NULL,
    AccountType VARCHAR,
    FOREIGN KEY (UserID) REFERENCES "User"(ID) ON DELETE CASCADE
);

CREATE TABLE Request (
    ID SERIAL PRIMARY KEY,
    CustomerID INT NOT NULL,
    TechnicianID INT NOT NULL,
    Status VARCHAR NOT NULL DEFAULT 'Pending',
    DeviceDeliveryMethod VARCHAR,
    CreatedDate DATE DEFAULT CURRENT_DATE,
    EstimatedTime TIMESTAMP,
    ActualTime TIMESTAMP,
    RequestType VARCHAR,
    FOREIGN KEY (CustomerID) REFERENCES Customer(ID) ON DELETE CASCADE,
    FOREIGN KEY (TechnicianID) REFERENCES Technician(ID) ON DELETE CASCADE
);

CREATE TABLE NewRequest (
    ID SERIAL PRIMARY KEY,
    IssueDescription VARCHAR NOT NULL,
    Title VARCHAR NOT NULL,
    Category VARCHAR NOT NULL,
    EstimatedCost DECIMAL (10, 2),
    ActualCost DECIMAL (10, 2) DEFAULT 0.00,
    MaintenanceTime INT,
    Image VARCHAR,
    RequestID INT NOT NULL,
    FOREIGN KEY (RequestID) REFERENCES Request(ID) ON DELETE CASCADE
);

CREATE TABLE Service (
    ID SERIAL PRIMARY KEY,
    CustomerID INT,
    Title VARCHAR,
    Category VARCHAR,
    ActualCost DECIMAL (10, 2) DEFAULT 0.00,
    MaintenanceTime INT,
    Image VARCHAR,
    IssueDescription VARCHAR,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UsageTime INT DEFAULT 0,
    IsCommon BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (CustomerID) REFERENCES Customer(ID) ON DELETE CASCADE
);

CREATE TABLE ServiceRequest (
    ID SERIAL PRIMARY KEY,
    ServiceID INT NOT NULL,
    RequestID INT NOT NULL,
    FOREIGN KEY (ServiceID) REFERENCES Service(ID) ON DELETE CASCADE,
    FOREIGN KEY (RequestID) REFERENCES Request(ID) ON DELETE CASCADE
);

CREATE TABLE Feedback (
    ID SERIAL PRIMARY KEY,
    CustomerID INT NOT NULL,
    ServiceID INT NOT NULL,
    Rating INT,
    Comment VARCHAR,
    FOREIGN KEY (CustomerID) REFERENCES Customer(ID) ON DELETE CASCADE,
    FOREIGN KEY (ServiceID) REFERENCES Service(ID) ON DELETE CASCADE
);

CREATE TABLE Article (
    ID SERIAL PRIMARY KEY,
    Title VARCHAR,
    Image VARCHAR,
    Description VARCHAR,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Report (
    ID SERIAL PRIMARY KEY,
    RequestID INT NOT NULL,
    Comment VARCHAR,
    FOREIGN KEY (RequestID) REFERENCES Request(ID) ON DELETE CASCADE
);

CREATE TABLE Spares (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR,
    Quantity INT,
    ReorderThreshold INT DEFAULT 20,
    Price DECIMAL(10, 2)
);

CREATE TABLE ReportDetails (
    ID SERIAL PRIMARY KEY,
    ReportID INT NOT NULL,
    SpareID INT NOT NULL,
    Quantity INT  DEFAULT 1,
    FOREIGN KEY (ReportID) REFERENCES Report(ID) ON DELETE CASCADE,
    FOREIGN KEY (SpareID) REFERENCES Spares(ID) ON DELETE CASCADE
);
